### ISSUE TITLE
`nextStation` variant not very reliable

### ISSUE THREAD

**Issue by deg0nz** [derhuerst/vbb-hafas#21]
Hey,

while implementing the new `nextStation` feature in my MagicMirror module, I noticed that the reliability of this method seems to be not so good. I assume this has to do with the VBB side of the service.

I get a Bad Gateway `504` error very often. Did you experience the same issues during your tests?

It seems to be more often on bus departures than on suburban lines though...

Greetings! And thank you very much for implementing this! ;)

**Comment by derhuerst** [comment]
I will dig into the logs to find requests that resulted in a `504`. It would be very useful if you gave me some example on where this fails often.

**Comment by derhuerst** [comment]
You may also want to test [`vbb-departures-in-direction`](https://github.com/derhuerst/vbb-departures-in-direction) in isolation.

**Comment by derhuerst** [comment]
As a test, I picked `900000024207` (*Kantstr./Leibnizstr.*), where `M49` & `X34` cross the `101` line. I fetched departures in direction of `900000024252` (*Schlüterstr.*):

```js
const depsInDirection = require('vbb-departures-in-direction')

const kantstrLeibnitzstr = '900000024207'
const schlueterstr = '900000024252'

depsInDirection(kantstrLeibnitzstr, schlueterstr, {when})
.then(console.log)
.catch(console.error)
```

It seems to work fine:

```js
[
	{
		ref: '1|18729|10|86|19082017',
		station: {
			type: 'station',
			name: 'Kantstr./Leibnizstr.',
			coordinates: {…},
			id: '900000024207',
			products: {…}
		},
		when: '2017-08-19T16:03:00+02:00',
		direction: 'S+U Zoologischer Garten',
		line: {
			type: 'line',
			name: 'M49',
			class: 8,
			productCode: 3,
			productName: 'MB',
			product: 'bus',
			mode: 'bus',
			id: 'm49',
			symbol: 'M',
			nr: 49,
			metro: true,
			express: false,
			night: false
		},
		remarks: [ null ],
		trip: 18729,
		delay: 480
	},
	{
		ref: '1|22024|13|86|19082017',
		station: {
			type: 'station',
			name: 'Kantstr./Leibnizstr.',
			coordinates: {…},
			id: '900000024207',
			products: {…}
		},
		when: '2017-08-19T15:59:00+02:00',
		direction: 'S+U Zoologischer Garten',
		line: {
			type: 'line',
			name: 'X34',
			class: 8,
			productCode: 3,
			productName: 'B',
			product: 'bus',
			mode: 'bus',
			id: 'x34',
			symbol: 'X',
			nr: 34,
			metro: false,
			express: true,
			night: false
		},
		remarks: [ null ],
		trip: 22024,
		delay: 540
	},
	{
		ref: '1|18699|9|86|19082017',
		station: {
			type: 'station',
			name: 'Kantstr./Leibnizstr.',
			coordinates: {…},
			id: '900000024207',
			products: {…}
		},
		when: '2017-08-19T16:07:00+02:00',
		direction: 'S+U Zoologischer Garten',
		line: {
			type: 'line',
			name: 'M49',
			class: 8,
			productCode: 3,
			productName: 'MB',
			product: 'bus',
			mode: 'bus',
			id: 'm49',
			symbol: 'M',
			nr: 49,
			metro: true,
			express: false,
			night: false
		},
		remarks: [ null ],
		trip: 18699,
		delay: 1320
	}
]
```

**Comment by derhuerst** [comment]
The `vbb.transport.rest` equivalent to work as well:

```shell
curl -v 'https://vbb.transport.rest/stations/900000024207/departures?nextStation=900000024252'
```

**Comment by deg0nz** [comment]
Okay, the tests I did where with Bus stations Lückstr./Weitlingstr. and Münsterlandplatz (as direction)  with IDs 900000160019 and 900000160733 respectively. The request takes very long and the following error gets returned:

``` html
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```
here's my cURL command: `curl 'https://vbb.transport.rest/stations/900000160019/departures?when=now&nextStation=900000160733'`
I tried other stations, they seem to work better.

I also just tried Alexanderplatz and Jannowitzbrücke (as direction) and get the following error:
```json
{"error":true,"msg":"HCI Service: request failed"}
```
But this means, the error is on the VBB side, right?

Here's my cURL: `curl 'https://vbb.transport.rest/stations/900000100004/departures?nextStation=900000100005&when=now'`
And here's the output with `-v`:

```
*   Trying 51.15.70.111...
* TCP_NODELAY set
* Connected to vbb.transport.rest (51.15.70.111) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: vbb.transport.rest
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET /stations/900000100004/departures?nextStation=900000100005&when=now HTTP/1.1
> Host: vbb.transport.rest
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 502 Bad Gateway
< Server: nginx/1.10.3 (Ubuntu)
< Date: Mon, 21 Aug 2017 20:33:24 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 50
< Connection: keep-alive
< X-Powered-By: vbb-rest https://github.com/derhuerst/vbb-rest
< Surrogate-Control: no-store
< Cache-Control: no-store, no-cache, must-revalidate, proxy-revalidate
< Pragma: no-cache
< Expires: 0
< ETag: W/"32-g1yCtKWat77YFBaGSPj0SeKUzrE"
< Vary: Accept-Encoding
<
* Connection #0 to host vbb.transport.rest left intact
{"error":true,"msg":"HCI Service: request failed"}%
```

When I let the code run on the mirror, it sometimes works ans sometimes not. But it seems to be very erratic...

I will reimplement the function with your `vbb-departures-in-direction` module and give you feedback when I tested it! It could take some days though, because time is rare at the moment...

**Comment by derhuerst** [comment]
> […] with Bus stations `Lückstr./Weitlingstr.` and `Münsterlandplatz` (as direction) with IDs `900000160019` and `900000160733` respectively. The request takes very long and the following error gets returned: […]

That is my fault. The `vbb-departures-in-direction` lookup underneath seems to take very long at this specific location. My nginx set up to send a `504 Gateway Time-out` after 8 seconds. **I increased it to 20 seconds now**, thanks.

> I also just tried Alexanderplatz and Jannowitzbrücke (as direction) and get the following error:
>
> ```
> {"error":true,"msg":"HCI Service: request failed"}
> ```
>
> But this means, the error is on the VBB side, right?

Correct, VBB side. In fact [their service is unavailable quite often](https://status.transport.rest).

> I will reimplement the function with your `vbb-departures-in-direction` module and give you feedback when I tested it!

Note that this is what I already do in `vbb.transport.rest`: [I you pass the `nextStation` parameter, it will use `vbb-departures-in-direction`, otherwise it won't.](https://github.com/derhuerst/vbb-rest/blob/556c370499b045a895a04273aa73a1ac5eb0660f/docs/index.md#get-stationsiddepartures)

You can query the VBB HAFAS endpoint on your own (using `vbb-departures-in-direction` and/or `vbb-hafas`), but that won't change anything about their uptime.

**Comment by deg0nz** [comment]
Okay, so the issue has nothing to do with your API. 
As I'm querying the service with the `nextStation` parameter, everything is right I think. So there's no need to use `vbb-departures-in-direction`. I didn't do any more tests about the timeout issue, but I assume it should work now...

Should we close this issue now?

**Comment by derhuerst** [comment]
> As I'm querying the service with the `nextStation` parameter, everything is right I think. So there's no need to use `vbb-departures-in-direction`.

Not really.

yup, let's close. reopen if you encounter more issues.
